# Generated by Django 4.2 on 2025-04-29 19:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('emergencies', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responder_type', models.CharField(choices=[('medical', 'Medical Responder'), ('police', 'Police Officer'), ('fire', 'Firefighter'), ('admin', 'Administrator')], max_length=20)),
                ('license_number', models.CharField(blank=True, max_length=50)),
                ('is_verified', models.BooleanField(default=False)),
                ('current_location', models.CharField(blank=True, max_length=100)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmergencyAlert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('received_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='pending', max_length=20)),
                ('emergency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='emergencies.emergency')),
                ('responder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='responders.responder')),
            ],
        ),
    ]
