# Generated by Django 4.2 on 2025-04-23 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='id_photo',
            field=models.ImageField(blank=True, null=True, upload_to='id_photos/'),
        ),
    ]
