# Generated by Django 4.2 on 2025-04-24 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_id_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('username', models.CharField(max_length=150)),
                ('user_id', models.CharField(max_length=255)),
                ('reason', models.TextField(blank=True, null=True)),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
