# Generated by Django 5.2 on 2025-04-29 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("emergencyreport", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="emergencyreport",
            name="urgency",
        ),
        migrations.AddField(
            model_name="emergencyreport",
            name="details",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="emergencyreport",
            name="severity",
            field=models.IntegerField(default=5),
        ),
        migrations.AlterField(
            model_name="emergencyreport",
            name="emergency_type",
            field=models.CharField(
                choices=[
                    ("fire", "Fire"),
                    ("medical", "Medical Emergency"),
                    ("crime", "Crime"),
                    ("accident", "Accident"),
                    ("other", "Other"),
                ],
                default="other",
                max_length=50,
            ),
        ),
    ]
